name: requester_client
description: requester客户端核心
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4

  # 公共组件
  requester_common:
    git:
      url: https://github.com/lvsecoto/requester.git
      path: packages/requester_common
      ref: 906f2f7

  # 获取运行信息
  path_provider: ^2.1.4
  package_info_plus: ^8.0.2
  network_info_plus: ^6.0.1

  # 网络发现
  nsd: ^3.0.0

  flutter_hooks: ^0.20.5

  # 同步
  synchronized: ^3.2.0

  # 通信
  protobuf: ^3.1.0
  grpc: ^4.0.0
  fixnum: ^1.1.0

  # 网络请求相关
  dio: ^5.6.0

  # 工具类
  uuid: ^4.4.2
  rxdart: ^0.28.0
#  flutter_app_installer: ^1.0.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
